[package]
name = "mini"
version = "7.3.1"
edition = "2024"

[dependencies]
termion = "4.0.5"
polling = "3.11.0"
arboard = "3.6.1"
regex = "1.11.3"
ropey = "1.6.1"
portable-pty = "0.9.0"
vte = "0.15.0"

[profile.release]
strip = "symbols"
codegen-units = 1
lto = "fat"
panic = "abort"
