[package]
name = "mini"
version = "5.0.0"
edition = "2024"

[dependencies]
termion = "4.0.5"
polling = "3.11.0"
arboard = "3.6.1"
regex = "1.11.3"

[profile.release]
strip = "symbols"
codegen-units = 1
lto = "fat"
panic = "abort"
